import { Connection, PublicKey } from '@solana/web3.js'
import { getConnection, getWalletPublicKey } from '@/lib/solana'
import { getDammSolPriceFromPoolState } from '@/lib/damm-price'

const SOL_MINT = 'So11111111111111111111111111111111111111112'
function toNumber(value: unknown): number { if (value == null) return 0; if (typeof value === 'number') return Number.isFinite(value) ? value : 0; if (typeof value === 'bigint') return Number(value); if (typeof value === 'string') return Number(value) || 0; if (typeof (value as any).toNumber === 'function') { try { return (value as any).toNumber() } catch {} } if (typeof (value as any).toString === 'function') return Number((value as any).toString()) || 0; return 0 }
function toBase58(value: unknown): string { if (value instanceof PublicKey) return value.toBase58(); if (value && typeof (value as any).toBase58 === 'function') return (value as any).toBase58(); return String(value ?? '') }
function numberOrNull(value: unknown): number | null { if (value == null) return null; const n = Number(value); return Number.isFinite(n) ? n : null }
function parseDecimalCount(value: unknown): number | null { if (value == null) return null; let n: number = typeof value === 'number' ? value : typeof value === 'bigint' ? Number(value) : typeof value === 'string' ? Number(value) : 0; return Number.isInteger(n) && n >= 0 && n <= 18 ? n : null }
function uiAmount(raw: unknown, decimals: number | null): number | null { if (decimals === null) return null; const amount = toNumber(raw); if (!Number.isFinite(amount) || amount <= 0) return 0; return amount / 10 ** decimals }
function normalizeSymbolPart(symbol: unknown): string { const s = String(symbol ?? '').trim(); return s.toUpperCase() === 'WSOL' ? 'SOL' : s }
async function getCpAmm(connection: Connection = getConnection()): Promise<any> { const { CpAmm } = await import('@meteora-ag/cp-amm-sdk'); return new CpAmm(connection) }
async function fetchMeteoraDammPositionFields(positionPubkey: string): Promise<any> { try { const res = await fetch(`https://amm-v2.meteora.ag/position/${positionPubkey}`, { headers: { Accept: 'application/json' }, signal: AbortSignal.timeout(5_000) }); if (!res.ok) return null; return await res.json() } catch { return null } }
async function fetchMeteoraDammPoolStats(poolAddress: string): Promise<{ volume24hUsd: number | null; tvlUsd: number | null } | null> { try { const res = await fetch(`https://amm-v2.meteora.ag/pool/${poolAddress}`, { headers: { Accept: 'application/json' }, signal: AbortSignal.timeout(5_000) }); if (!res.ok) return null; const data = await res.json(); return { volume24hUsd: Number(data.trading_volume ?? data.volume_24h ?? 0) || null, tvlUsd: Number(data.pool_tvl ?? data.tvl ?? 0) || null } } catch { return null } }
export async function fetchLiveDammPositions(connection: Connection = getConnection()): Promise<any[]> { const walletPublicKey = getWalletPublicKey(); const sdk = await getCpAmm(connection); const userPositions = await sdk.getPositionsByUser(walletPublicKey); const live: any[] = []; for (const item of userPositions) { const positionPubkey = toBase58(item.position); if (!positionPubkey) continue; const positionState = item.positionState ?? {}; const poolAddress = toBase58(positionState.pool); if (!poolAddress) continue; let poolState: any = null; try { poolState = await sdk.fetchPoolState(new PublicKey(poolAddress)) } catch {} const meteoraFields = await fetchMeteoraDammPositionFields(positionPubkey); const mint = toBase58(poolState?.tokenAMint) || toBase58(poolState?.tokenBMint) || poolAddress; const dammPrice = poolState ? await getDammSolPriceFromPoolState(connection, poolState) : null; const currentPrice = dammPrice?.solPerToken ?? 0; const claimableFeesUsd = meteoraFields?.claimableFeesUsd ?? null; const positionValueUsd = meteoraFields?.positionValueUsd ?? null; const totalPnlUsd = meteoraFields?.totalPnlUsd ?? null; live.push({ id: `meteora-damm-${positionPubkey}`, mint, symbol: 'DAMM', pool_address: poolAddress, position_pubkey: positionPubkey, strategy_id: 'damm-live', position_type: 'damm-edge', status: 'active', in_range: true, opened_at: new Date().toISOString(), current_price: currentPrice, pnl_usd: totalPnlUsd, metadata: { source_of_truth: 'meteora', position_kind: 'damm-v2' }, _source: 'meteora-live' }); } return live }
