import { Connection, PublicKey } from '@solana/web3.js'
import { getConnection, getWalletPublicKey, getRpcEndpointCandidates, createConnection } from '@/lib/solana'
import { getDammSolPriceFromPoolState } from '@/lib/damm-price'

const SOL_MINT = 'So11111111111111111111111111111111111111112'
const METEORA_DLMM_POSITION_API = 'https://dlmm-api.meteora.ag/position'
const DLMM_POSITION_STATS_CACHE_TTL_MS = 60_000
const _dlmmPositionStatsCache = new Map<string, { value: Record<string, number | null> | null; expiresAt: number }>()
const PNL_PCT_KEYS = ['position_pnl_pct', 'position_pnl_percentage', 'pnl_pct', 'pnl_percentage', 'total_pnl_pct', 'total_pnl_percentage', 'pnlPercent', 'pnlPercentage']

function toNumber(value: unknown): number { if (value == null) return 0; if (typeof value === 'number') return Number.isFinite(value) ? value : 0; if (typeof value === 'bigint') return Number(value); if (typeof value === 'string') return Number(value) || 0; if (typeof (value as any).toNumber === 'function') { try { return (value as any).toNumber() } catch {} } if (typeof (value as any).toString === 'function') return Number((value as any).toString()) || 0; return 0 }

function numberOrNull(value: unknown): number | null { if (value == null) return null; const n = Number(value); return Number.isFinite(n) ? n : null }

function toBase58(value: unknown): string { if (value instanceof PublicKey) return value.toBase58(); if (value && typeof (value as any).toBase58 === 'function') return (value as any).toBase58(); return String(value ?? '') }

function getCached<T>(cache: Map<string, { value: T; expiresAt: number }>, key: string): T | undefined { const cached = cache.get(key); if (!cached) return undefined; if (cached.expiresAt > Date.now()) return cached.value; cache.delete(key); return undefined }

function setCached<T>(cache: Map<string, { value: T; expiresAt: number }>, key: string, value: T, ttlMs: number): void { cache.set(key, { value, expiresAt: Date.now() + ttlMs }) }

function getFirstFiniteRecordNumber(record: Record<string, unknown>, keys: string[]): number | null { for (const key of keys) { const value = numberOrNull(record[key]); if (value !== null) return value } return null }

export async function fetchMeteoraDlmmPositionStats(positionPubkey: string): Promise<Record<string, number | null> | null> { if (!positionPubkey) return null; const cached = getCached(_dlmmPositionStatsCache, positionPubkey); if (cached !== undefined) return cached; try { const res = await fetch(`${METEORA_DLMM_POSITION_API}/${positionPubkey}`, { headers: { Accept: 'application/json' }, signal: AbortSignal.timeout(5_000) }); if (!res.ok) { setCached(_dlmmPositionStatsCache, positionPubkey, null, DLMM_POSITION_STATS_CACHE_TTL_MS); return null } const data = await res.json(); const stats = { daily_fee_yield: Number(data.daily_fee_yield ?? NaN), fee_apr_24h: Number(data.fee_apr_24h ?? NaN), fee_apy_24h: Number(data.fee_apy_24h ?? NaN), total_fee_usd_claimed: Number(data.total_fee_usd_claimed ?? NaN), total_reward_usd_claimed: Number(data.total_reward_usd_claimed ?? NaN), position_pnl_usd: Number(data.position_pnl_usd ?? data.pnl_usd ?? data.total_pnl_usd ?? NaN), position_pnl_pct: getFirstFiniteRecordNumber(data, PNL_PCT_KEYS) ?? Number.NaN }; const normalized = Object.fromEntries(Object.entries(stats).map(([key, value]) => [key, Number.isFinite(value) ? value : null])) as Record<string, number | null>; setCached(_dlmmPositionStatsCache, positionPubkey, normalized, DLMM_POSITION_STATS_CACHE_TTL_MS); return normalized } catch { setCached(_dlmmPositionStatsCache, positionPubkey, null, DLMM_POSITION_STATS_CACHE_TTL_MS); return null } }

export async function fetchLiveDlmmPositions(connection: Connection = getConnection()): Promise<any[]> { const walletPublicKey = getWalletPublicKey(); const DLMM = await (await import('@meteora-ag/dlmm')).default as any; const allPositions: Map<string, any> = await DLMM.getAllLbPairPositionsByUser(connection, walletPublicKey); const live: any[] = []; for (const [mapPoolAddress, positionInfo] of allPositions) { const poolAddress = toBase58(positionInfo?.publicKey) || mapPoolAddress; const positions = Array.isArray(positionInfo?.lbPairPositionsData) ? positionInfo.lbPairPositionsData : Array.isArray(positionInfo?.userPositions) ? positionInfo.userPositions : positionInfo?.publicKey && positionInfo?.positionData ? [positionInfo] : []; if (positions.length === 0) continue; const mint = toBase58(positionInfo?.tokenX?.publicKey) || toBase58(positionInfo?.tokenY?.publicKey) || poolAddress; let currentPrice = 0; try { const dlmmPool = await DLMM.create(connection, new PublicKey(poolAddress)); const activeBin = await dlmmPool.getActiveBin(); currentPrice = Number(activeBin.pricePerToken) || 0 } catch {} for (const pos of positions) { const positionPubkey = toBase58(pos.publicKey); if (!positionPubkey) continue; const positionData = pos.positionData ?? {}; const positionStats = await fetchMeteoraDlmmPositionStats(positionPubkey); const solDeposited = Number(positionData.totalXAmount ?? 0) / 1e9 || Number(positionData.totalYAmount ?? 0) / 1e9 || 0; const positionPnlUsd = positionStats?.position_pnl_usd ?? null; const positionPnlPct = positionStats?.position_pnl_pct ?? null; live.push({ id: `meteora-${positionPubkey}`, mint, symbol: 'LIVE', pool_address: poolAddress, position_pubkey: positionPubkey, strategy_id: 'meteora-live', position_type: 'dlmm', status: 'active', in_range: true, opened_at: new Date().toISOString(), sol_deposited: solDeposited, current_price: currentPrice, pnl_usd: positionPnlUsd, pnl_pct: positionPnlPct, metadata: { source_of_truth: 'meteora' }, _source: 'meteora-live' }); } } return live }
